import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        
        {/* This "children" is where your specific page content loads */}
        <main>{children}</main>

        {/* Simple Bottom Bar */}
        <footer className="w-full py-4 border-t border-gray-200 text-center text-sm text-gray-500 bg-white">
          © 2026 SynticAI. All rights reserved. | Trusted AI Solutions
        </footer>
      </body>
    </html>
  );
}
